version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: tascas203-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: joel
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
